// Generated by CoffeeScript 1.8.0

(function() {
	var sum;
	
	sum = function(a, b, c) {
	    return d (a*1 + b*2 + c*3);		//Kaffee 1€, Tee 2€, Brühe 3€
	};
  
    $("#button").click(function() {
        var a, b, c;
        a  = $("#a").val();
        b1 = $("#b").val();
        b2 = $("#b").val();
        b3 = $("#b").val();
	    c  = $("#c").val();
        return $("#d").html(sum(a, b, c));
  });
  
}).call(this);