// Generated by CoffeeScript 1.8.0

var Gemüsebrühe;
Gemüsebrühe = (function(){
  function Gemüsebrühe() {}
  return Gemüsebrühe;
}) ();


class Gemüsebrühe
  constructor: (@name) ->

  price: (euro) ->
    alert @name + " price #{euro}m."

  menge: (stück) ->
    alert @name + " menge #{stück}m."