// Generated by CoffeeScript 1.8.0

var Kaffee;
Kaffee = (function(){
  function Kaffee() {}
  return Kaffee;
}) ();


class Kaffee
  constructor: (@name) ->

  price: (euro) ->
    alert @name + " price #{euro}m."

  menge: (stück) ->
    alert @name + " menge #{stück}m."