// Generated by CoffeeScript 1.8.0

var Tee;
Tee = (function(){
  function Tee() {}
  return Tee;
}) ();


class Tee
  constructor: (@name) ->

  price: (euro) ->
    alert @name + " price #{euro}m."

  menge: (stück) ->
    alert @name + " menge #{stück}m."


class Gruener extends Tee
  price: ->
    alert "gruen"
    super 5

class Schwarzer extends Tee
  price: ->
    alert "schwarz"
    super 22

class Früchte extends Tee
  price: ->
    alert "früchte"
    super 45
